<?php $baseUrl = $block->getBaseUrl(); ?>
<?php $_productCollection = $block->getProductCollection(); ?>
<?php if ($block->getData('recommended') && $block->getCustomerLoggedIn()->isLoggedIn()): ?>
<div class="block widget block-new-products grid bestsale">
    <div class="products-display ">
        <div class="sub_product_display">
            <div class="products-show">
                <div class="block-title">
                    <h2 role="heading" aria-level="2"><?= $block->getData('recommended'); ?></h2>
                    <?php if (count($_productCollection) == 0) :?>
                    <div class="message info empty"><div><?= $block->escapeHtml(__('We can\'t find products matching the selection.')) ?></div></div>
                    <?php endif; ?>
                </div>
            </div>
            <div id="content-loader" class="slider">
            </div>
            <div id="ajax_loading" class="ajax_loading" style="display: none">
            </div>
            <input type="hidden" value="<?php echo $baseUrl . 'recommended/slider/products'; ?>" id="baseUrl"/>
        </div>
    </div>

</div>
<?php endif; ?>

<script type="text/javascript">
    require(['jquery', 'jquery/ui', 'owlCarousel'], function ($, owlCarousel) {
        jQuery(document).ready(function (jQuery) {
            var url = "<?php echo $baseUrl . 'recommended/slider/products'; ?>";
            $.ajax({
                url: url,
                type: "POST",
                data: {sucess: 'success'},
                showLoader: true,
                cache: false,
                success: function (response) {
                    htmlObject = jQuery('#content-loader').html(response);
                    htmlObject.find('[data-role=tocart-form], .form.map.checkout').attr('data-mage-init', JSON.stringify({'catalogAddToCart': {}}));
                    htmlObject.trigger('contentUpdated');
                    var owl = jQuery('.owlslider');
                    owl.owlCarousel({
                        items: 4,
                        loop: false,
                        margin: 10,
                        autoplay: true,
                        showLoader: true,
                        autoplayHoverPause: true,
                        autoplaySpeed: 500,
                        slideBy: 1,
                        responsiveClass: true,
                        nav: true,
                        responsive: {
                            0: {
                                items: 1
                            },
                            600: {
                                items: 3
                            },
                            1000: {
                                items: 5
                            }
                        }
                    });
                }
            });
        });
    });
</script>


<script type="text/javascript">
    require(['jquery', 'jquery/ui'], function ($) {
        jQuery(document).on("click", ".action.tocart.primary", function () {
            var product_id = jQuery(this).parent('form').find('.product-id').val();
            var customurl = "<?php echo $this->getUrl() . 'recommended/slider/addtocart' ?>";
            if (product_id) {
                $.ajax({
                    url: customurl,
                    type: 'POST',
                    dataType: 'json',
                    data: {
                        product_id: product_id,
                    },
                    success: function (response) {
                        if (response != null) {
                            if (response.output) {
                                console.log(response.output);
                            }
                        }
                    },
                    error: function (xhr, status, errorThrown) {
                        console.log(errorThrown);
                    }
                });
            }
        });
    });
</script>

